# Generated by Django 4.1.1 on 2022-12-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0004_stavki_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stavki_New',
        ),
    ]
