# Generated by Django 4.1.1 on 2023-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0007_stavki_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='stavki',
            name='Status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
