# Generated by Django 4.1.1 on 2022-12-06 07:25

from django.db import migrations, models
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tournament', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('dicription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country_id', models.IntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('dicription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_id')),
                ('summ', models.IntegerField(db_column='Summ')),
                ('time', models.DateTimeField()),
                ('koeff', models.FloatField()),
                ('match_id', models.IntegerField(db_column='Match__id')),
            ],
            options={
                'db_table': 'stavki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cap', models.CharField(max_length=50)),
                ('country_id', models.IntegerField()),
                ('organization_id', models.IntegerField()),
                ('award_id', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('esports_id', models.IntegerField()),
                ('dicription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
