# Generated by Django 4.1.1 on 2022-12-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stavki_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_id')),
                ('summ', models.IntegerField(db_column='Summ')),
                ('time', models.DateTimeField()),
                ('koeff', models.FloatField()),
                ('match_id', models.IntegerField(db_column='Match__id')),
            ],
            options={
                'db_table': 'stavki',
                'managed': False,
            },
        ),
    ]
