# Generated by Django 4.1.1 on 2022-12-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0005_delete_stavki_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stavki',
            options={'managed': True},
        ),
    ]
