# Generated by Django 4.1.1 on 2023-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_2', '0008_stavki_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavki',
            name='Status',
            field=models.IntegerField(db_column='Status'),
        ),
    ]
